import macros

macro view*(body: untyped): untyped =
  result = newStmtList()
  result.add(
    newNimNode(nnkImportStmt).add(
       newIdentNode("dom")
    )
  )
  result.add(
    newStmtList(
      newAssignment(
        newDotExpr(
          newDotExpr(
            newIdentNode("dom"),
            newIdentNode("window")
          ),
          newIdentNode("onload")
        ),
        newNimNode(nnkLambda).add(
          newEmptyNode(),
          newEmptyNode(),
          newEmptyNode(),
          newNimNode(nnkFormalParams).add(
            newEmptyNode(),
            newIdentDefs(
              newIdentNode("e"),
              newDotExpr(
                newIdentNode("dom"),
                newIdentNode("Event")
              ),
              newEmptyNode()
            )
          ),
          newEmptyNode(),
          newEmptyNode(),
          newStmtList(
            newNimNode(nnkVarSection).add(
              newIdentDefs(
                newIdentNode("canvas"),
                newEmptyNode(),
                newDotExpr(
                  newCall(
                    newDotExpr(
                      newDotExpr(
                        newIdentNode("dom"),
                        newIdentNode("document")
                      ),
                      newIdentNode("getElementById")
                    ),
                    newStrLitNode("MyCanvas")
                  ),
                  newIdentNode("Canvas")
                )
              )
            ),
            newNimNode(nnkVarSection).add(
              newIdentDefs(
                newIdentNode("context"),
                newEmptyNode(),
                newCall(
                  newDotExpr(
                    newIdentNode("canvas"),
                    newIdentNode("getContext2d")
                  )
                )
              )
            ),
            copyNimTree(body)
          )
        )
      )
    )
  )